<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ajout d'un type de plat</title>
</head>
<body>
    <h1>Ajout d'un type de plat</h1>
    <form action="save_category.php" method="POST">
        <input type="text" name="categoryTitle" placeholder="Choisissez le nom" required>
        <button type="submit">Enregistrer</button>
    </form>
</body>
</html>