<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Modification d'un type de plat</h1>
    <form action="update_category.php" method="POST">
        <input type="hidden" name="categoryId" value="<?= $category['Id']; ?>">
        <input type="text" name="categoryTitle" value="<?= $category['title']; ?>" placeholder="Choisissez le nom" required>
        <button type="submit">Enregistrer</button>
    </form>
</body>
</html>