
<body>
    <main>
        <form method="POST" action="userController.php?task=register">
            <h1>Inscription</h1>
            <input type="text" placeholder="Adresse email" name="email">
            <input type="password" placeholder="Mot de passe" name="password">
            <input type="password" placeholder="confirmation de mot de passe" name="passwordConfirm">
            <input type="text" placeholder="Pseudo" name="username">
            <button type="submit">Inscription</button>
            
        </form>
    </main>
    <footer>
        <p>&copy; 3WA Projet Restaurant 2018</p>
        
    </footer>
</body>
</html>