
<body>
    <main>
        <form method="POST" action="userController.php?task=authentication">
            <h1>Login</h1>
            <input type="email" placeholder="Adresse email" name="email">
            <input type="password" placeholder="Mot de passe" name="password">
            <button type="submit">Connexion</button>
            
        </form>
    </main>
    <footer>
        <p>&copy; 3WA Projet Restaurant 2018</p>
        
    </footer>
</body> 
</html>