
<body>
    <form action="orderController.php?task=saveOrder" method="POST">
        <input type="text" name="lastname" placeholder="Nom" required>
        <input type="text" name="firstname" placeholder="Prénom" required>
        <input type="text" name="email" placeholder="Adresse email" required>
        <input type="text" name="phoneNumber" placeholder="Numéro de téléphone" required>
        <input type="text" name="address" placeholder="Adresse" required>
        <input type="text" name="postalCode" placeholder="Code postal" required>
        <input type="text" name="city" placeholder="Ville" required>
        <textarea name="review" placeholder="Commentaire"></textarea>
        <button type="submit">Valider</button>
    </form>
</body>
</html>