<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ajouter un client</title>
</head>
<body>
    <h1>Création d'un compte client</h1>
    <form action="save_client.php" method="POST">
        <input type="text" name="lastname" placeholder="Indiquez le nom du client" required>
        <input type="text" name="firstname" placeholder="Indiquez le prénom du client" required>
        <input type="number" name="phoneNumber" placeholder="Indiquez le numéro de téléphone" required>
        <input type="text" name="email" placeholder="Indiquez l'adresse email" required>
        <input type="text" name="password" placeholder="Indiquez le mot de passe" required>
        <button type="submit">Enregistrer</button>
    </form>
</body>
</html>